### ISSUE TITLE
Receiving / Transmitting on same Host

### ISSUE THREAD

**Issue by localleon** [Hundemeier/go-sacn#3]
OS: Linux
Version: latest

If you run a sACN-Receiver on your Host and the start a sACN-Transmitter. You get the following error. 
``` 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4df4fa]

goroutine 1 [running]:
github.com/Hundemeier/go-sacn/sacn.NewTransmitter(0x0, 0x0, 0x35c1711ec70da98e, 0xb1f8cce947e4eb8e, 0x53431f, 0x8, 0, 0x0, 0x0, 0x0, ...)
        /home/linuxleon/bin/Golang/src/github.com/Hundemeier/go-sacn/sacn/transmitter.go:43 +0x19a
main.main()
        /home/linuxleon/bin/key2sACN/key2sacn.go:43 +0x2e7
```

You can reproduce the error with the sample code.

**Comment by Hundemeier** [comment]
This is because multiple processes can not listen via UDP on the same port. The error you are facing is actually a null pointer exception, that is not handled.
I will rewrite the errorhanding of the `Receiver` function and currently the transmitter is using the same port (5568) as the receiver.

**Comment by localleon** [comment]
Does the Standard allow to change the Port of the Transmitter so sending and transmitting at the same time would be possible ?
